# coding: utf-8

"""
    Ex Libris APIs

    For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Fee(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'link': 'str',
        'type': 'object',
        'status': 'object',
        'original_amount': 'float',
        'creation_time': 'date',
        'comment': 'str',
        'owner': 'object',
        'title': 'str',
        'barcode': 'object',
        'transaction': 'list[object]',
        'bursar_transaction_id': 'str'
    }

    attribute_map = {
        'link': 'link',
        'type': 'type',
        'status': 'status',
        'original_amount': 'original_amount',
        'creation_time': 'creation_time',
        'comment': 'comment',
        'owner': 'owner',
        'title': 'title',
        'barcode': 'barcode',
        'transaction': 'transaction',
        'bursar_transaction_id': 'bursar_transaction_id'
    }

    def __init__(self, link=None, type=None, status=None, original_amount=None, creation_time=None, comment=None, owner=None, title=None, barcode=None, transaction=None, bursar_transaction_id=None):  # noqa: E501
        """Fee - a model defined in Swagger"""  # noqa: E501
        self._link = None
        self._type = None
        self._status = None
        self._original_amount = None
        self._creation_time = None
        self._comment = None
        self._owner = None
        self._title = None
        self._barcode = None
        self._transaction = None
        self._bursar_transaction_id = None
        self.discriminator = None
        if link is not None:
            self.link = link
        if type is not None:
            self.type = type
        if status is not None:
            self.status = status
        if original_amount is not None:
            self.original_amount = original_amount
        if creation_time is not None:
            self.creation_time = creation_time
        if comment is not None:
            self.comment = comment
        if owner is not None:
            self.owner = owner
        if title is not None:
            self.title = title
        if barcode is not None:
            self.barcode = barcode
        if transaction is not None:
            self.transaction = transaction
        if bursar_transaction_id is not None:
            self.bursar_transaction_id = bursar_transaction_id

    @property
    def link(self):
        """Gets the link of this Fee.  # noqa: E501


        :return: The link of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this Fee.


        :param link: The link of this Fee.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def type(self):
        """Gets the type of this Fee.  # noqa: E501

        The fine / fee type. Mandatory.  # noqa: E501

        :return: The type of this Fee.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Fee.

        The fine / fee type. Mandatory.  # noqa: E501

        :param type: The type of this Fee.  # noqa: E501
        :type: object
        """

        self._type = type

    @property
    def status(self):
        """Gets the status of this Fee.  # noqa: E501

        The fine / fee status.  # noqa: E501

        :return: The status of this Fee.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Fee.

        The fine / fee status.  # noqa: E501

        :param status: The status of this Fee.  # noqa: E501
        :type: object
        """

        self._status = status

    @property
    def original_amount(self):
        """Gets the original_amount of this Fee.  # noqa: E501

        The fine / fee original amount. Mandatory for POST.  # noqa: E501

        :return: The original_amount of this Fee.  # noqa: E501
        :rtype: float
        """
        return self._original_amount

    @original_amount.setter
    def original_amount(self, original_amount):
        """Sets the original_amount of this Fee.

        The fine / fee original amount. Mandatory for POST.  # noqa: E501

        :param original_amount: The original_amount of this Fee.  # noqa: E501
        :type: float
        """

        self._original_amount = original_amount

    @property
    def creation_time(self):
        """Gets the creation_time of this Fee.  # noqa: E501

        Date the fine / fee was created.  # noqa: E501

        :return: The creation_time of this Fee.  # noqa: E501
        :rtype: date
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this Fee.

        Date the fine / fee was created.  # noqa: E501

        :param creation_time: The creation_time of this Fee.  # noqa: E501
        :type: date
        """

        self._creation_time = creation_time

    @property
    def comment(self):
        """Gets the comment of this Fee.  # noqa: E501

        Fine / fee comment.  # noqa: E501

        :return: The comment of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Fee.

        Fine / fee comment.  # noqa: E501

        :param comment: The comment of this Fee.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def owner(self):
        """Gets the owner of this Fee.  # noqa: E501

        The fine / fee owner. Mandatory for POST.  # noqa: E501

        :return: The owner of this Fee.  # noqa: E501
        :rtype: object
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Fee.

        The fine / fee owner. Mandatory for POST.  # noqa: E501

        :param owner: The owner of this Fee.  # noqa: E501
        :type: object
        """

        self._owner = owner

    @property
    def title(self):
        """Gets the title of this Fee.  # noqa: E501

        The item title.  # noqa: E501

        :return: The title of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Fee.

        The item title.  # noqa: E501

        :param title: The title of this Fee.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def barcode(self):
        """Gets the barcode of this Fee.  # noqa: E501

        The item barcode.  # noqa: E501

        :return: The barcode of this Fee.  # noqa: E501
        :rtype: object
        """
        return self._barcode

    @barcode.setter
    def barcode(self, barcode):
        """Sets the barcode of this Fee.

        The item barcode.  # noqa: E501

        :param barcode: The barcode of this Fee.  # noqa: E501
        :type: object
        """

        self._barcode = barcode

    @property
    def transaction(self):
        """Gets the transaction of this Fee.  # noqa: E501

        A list of transactions.  # noqa: E501

        :return: The transaction of this Fee.  # noqa: E501
        :rtype: list[object]
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction):
        """Sets the transaction of this Fee.

        A list of transactions.  # noqa: E501

        :param transaction: The transaction of this Fee.  # noqa: E501
        :type: list[object]
        """

        self._transaction = transaction

    @property
    def bursar_transaction_id(self):
        """Gets the bursar_transaction_id of this Fee.  # noqa: E501

        The unique sequence used for the fine/fee identification when communicating with the Bursar system.  # noqa: E501

        :return: The bursar_transaction_id of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._bursar_transaction_id

    @bursar_transaction_id.setter
    def bursar_transaction_id(self, bursar_transaction_id):
        """Sets the bursar_transaction_id of this Fee.

        The unique sequence used for the fine/fee identification when communicating with the Bursar system.  # noqa: E501

        :param bursar_transaction_id: The bursar_transaction_id of this Fee.  # noqa: E501
        :type: str
        """

        self._bursar_transaction_id = bursar_transaction_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Fee, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Fee):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
