# coding: utf-8

"""
    Ex Libris APIs

    For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ResearcherOrganizationAffiliation2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'organization_code': 'str',
        'organization_name': 'str',
        'start_date': 'date',
        'end_date': 'date',
        'position': 'str'
    }

    attribute_map = {
        'organization_code': 'organization_code',
        'organization_name': 'organization_name',
        'start_date': 'start_date',
        'end_date': 'end_date',
        'position': 'position'
    }

    def __init__(self, organization_code=None, organization_name=None, start_date=None, end_date=None, position=None):  # noqa: E501
        """ResearcherOrganizationAffiliation2 - a model defined in Swagger"""  # noqa: E501
        self._organization_code = None
        self._organization_name = None
        self._start_date = None
        self._end_date = None
        self._position = None
        self.discriminator = None
        if organization_code is not None:
            self.organization_code = organization_code
        if organization_name is not None:
            self.organization_name = organization_name
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if position is not None:
            self.position = position

    @property
    def organization_code(self):
        """Gets the organization_code of this ResearcherOrganizationAffiliation2.  # noqa: E501

        The researcher's organization affiliation code.  # noqa: E501

        :return: The organization_code of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :rtype: str
        """
        return self._organization_code

    @organization_code.setter
    def organization_code(self, organization_code):
        """Sets the organization_code of this ResearcherOrganizationAffiliation2.

        The researcher's organization affiliation code.  # noqa: E501

        :param organization_code: The organization_code of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :type: str
        """

        self._organization_code = organization_code

    @property
    def organization_name(self):
        """Gets the organization_name of this ResearcherOrganizationAffiliation2.  # noqa: E501

        The researcher's organization affiliation name.  # noqa: E501

        :return: The organization_name of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :rtype: str
        """
        return self._organization_name

    @organization_name.setter
    def organization_name(self, organization_name):
        """Sets the organization_name of this ResearcherOrganizationAffiliation2.

        The researcher's organization affiliation name.  # noqa: E501

        :param organization_name: The organization_name of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :type: str
        """

        self._organization_name = organization_name

    @property
    def start_date(self):
        """Gets the start_date of this ResearcherOrganizationAffiliation2.  # noqa: E501

        The researcher's organization affiliation start date.  # noqa: E501

        :return: The start_date of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ResearcherOrganizationAffiliation2.

        The researcher's organization affiliation start date.  # noqa: E501

        :param start_date: The start_date of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :type: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ResearcherOrganizationAffiliation2.  # noqa: E501

        The researcher's organization affiliation end date.  # noqa: E501

        :return: The end_date of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ResearcherOrganizationAffiliation2.

        The researcher's organization affiliation end date.  # noqa: E501

        :param end_date: The end_date of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :type: date
        """

        self._end_date = end_date

    @property
    def position(self):
        """Gets the position of this ResearcherOrganizationAffiliation2.  # noqa: E501

        The researcher's position.  # noqa: E501

        :return: The position of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this ResearcherOrganizationAffiliation2.

        The researcher's position.  # noqa: E501

        :param position: The position of this ResearcherOrganizationAffiliation2.  # noqa: E501
        :type: str
        """

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResearcherOrganizationAffiliation2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResearcherOrganizationAffiliation2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
